DESKTOP_ICONS = [
    {'id': 'file-hunt', 'label': 'FILE_HUNT.EXE', 'kind': 'exe', 'window': 'file-hunt', 'x': 42, 'y': 38},
    {'id': 'flappy-bat', 'label': 'BAT_SLEEP.EXE', 'kind': 'exe', 'window': 'flappy-bat', 'x': 316, 'y': 246},
    {'id': 'memory-cards', 'label': 'photo_pairs.exe', 'kind': 'exe', 'window': 'memory-cards', 'x': 650, 'y': 396},
    {'id': 'cmd', 'label': 'MS-DOS.exe', 'kind': 'cmd', 'window': 'cmd', 'x': 78, 'y': 212},
    {'id': 'maze', 'label': 'Folders', 'kind': 'folder', 'window': 'explorer-maze', 'x': 286, 'y': 44},
    {'id': 'notes', 'label': 'readme_first.txt', 'kind': 'txt', 'window': 'readme', 'x': 592, 'y': 72},
    {'id': 'pixel-1', 'label': 'p1.png', 'kind': 'image', 'window': 'pixel-1', 'x': 458, 'y': 96},
    {'id': 'pixel-2', 'label': 'p2.png', 'kind': 'image', 'window': 'pixel-2', 'x': 724, 'y': 214},
    {'id': 'pixel-3', 'label': 'p3.png', 'kind': 'image', 'window': 'pixel-3', 'x': 476, 'y': 292},
    {'id': 'pixel-4', 'label': 'p4.png', 'kind': 'image', 'window': 'pixel-4', 'x': 826, 'y': 350},
    {'id': 'trash', 'label': 'Корзина', 'kind': 'trash', 'window': 'trash', 'x': 880, 'y': 116},
    {'id': 'sys', 'label': 'system32_backup', 'kind': 'folder', 'window': 'system-folder', 'x': 226, 'y': 330},
    {'id': 'lost', 'label': '~lost memories', 'kind': 'unknown', 'window': 'lost', 'x': 510, 'y': 352},
    {'id': 'antivirus', 'label': 'AVSCAN.exe', 'kind': 'shield', 'window': 'antivirus', 'x': 158, 'y': 462},
    {'id': 'paint', 'label': 'PAINT.exe', 'kind': 'paint', 'window': 'paint', 'x': 388, 'y': 478},
    {'id': 'music', 'label': 'PLAYER.exe', 'kind': 'music', 'window': 'music', 'x': 38, 'y': 332},
]

WINDOWS = {
    'file-hunt': {
        'title': 'FILE_HUNT.EXE',
        'url': '/games/file-hunt/',
        'width': 860,
        'height': 620,
        'x': 150,
        'y': 58,
        'load': 'htmx',
    },
    'flappy-bat': {
        'title': 'BAT_SLEEP.EXE',
        'url': '/games/flappy-bat/',
        'width': 620,
        'height': 500,
        'x': 190,
        'y': 76,
        'load': 'htmx',
    },
    'memory-cards': {
        'title': 'photo_pairs.exe',
        'url': '/games/memory-cards/',
        'width': 760,
        'height': 620,
        'x': 170,
        'y': 58,
        'load': 'htmx',
    },
    'cmd': {
        'title': 'MS-DOS Prompt',
        'url': '/games/cmd/',
        'width': 660,
        'height': 420,
        'x': 188,
        'y': 120,
        'load': 'htmx',
    },
    'explorer-maze': {
        'title': 'Explorer Maze',
        'url': '/games/explorer-maze/',
        'width': 700,
        'height': 500,
        'x': 210,
        'y': 88,
        'load': 'htmx',
    },
    'antivirus': {
        'title': 'AVSCAN.exe',
        'url': '/games/antivirus/',
        'width': 720,
        'height': 560,
        'x': 200,
        'y': 70,
        'load': 'htmx',
    },
    'paint': {
        'title': 'PAINT.exe — pixel restoration',
        'template': 'desktop/windows/paint_stub.html',
        'width': 720,
        'height': 540,
        'x': 220,
        'y': 88,
    },
    'music': {
        'title': 'PLAYER.exe',
        'template': 'desktop/windows/music.html',
        'width': 460,
        'height': 460,
        'x': 240,
        'y': 90,
    },
    'readme': {
        'title': 'readme_first.txt - Notepad',
        'template': 'desktop/windows/readme.html',
        'width': 520,
        'height': 360,
        'x': 330,
        'y': 130,
    },
    'pixel-1': {'title': 'p1.png', 'template': 'desktop/windows/image_file.html', 'src': '/static/img/pixel/p1.png', 'width': 520, 'height': 420, 'x': 300, 'y': 84},
    'pixel-2': {'title': 'p2.png', 'template': 'desktop/windows/image_file.html', 'src': '/static/img/pixel/p2.png', 'width': 520, 'height': 420, 'x': 330, 'y': 104},
    'pixel-3': {'title': 'p3.png', 'template': 'desktop/windows/image_file.html', 'src': '/static/img/pixel/p3.png', 'width': 520, 'height': 420, 'x': 360, 'y': 124},
    'pixel-4': {'title': 'p4.png', 'template': 'desktop/windows/image_file.html', 'src': '/static/img/pixel/p4.png', 'width': 520, 'height': 420, 'x': 390, 'y': 144},
    'meme-1': {'title': 'images.jpeg', 'template': 'desktop/windows/image_file.html', 'src': '/static/img/memes/images.jpeg', 'width': 560, 'height': 430, 'x': 300, 'y': 90},
    'meme-2': {'title': 'images-2.jpeg', 'template': 'desktop/windows/image_file.html', 'src': '/static/img/memes/images-2.jpeg', 'width': 560, 'height': 430, 'x': 320, 'y': 110},
    'meme-3': {'title': 'images-3.jpeg', 'template': 'desktop/windows/image_file.html', 'src': '/static/img/memes/images-3.jpeg', 'width': 560, 'height': 430, 'x': 340, 'y': 130},
    'asset-1': {'title': '1.png', 'template': 'desktop/windows/image_file.html', 'src': '/static/img/assets/asset_1.png', 'width': 620, 'height': 460, 'x': 300, 'y': 90},
    'asset-2': {'title': '2.png', 'template': 'desktop/windows/image_file.html', 'src': '/static/img/assets/asset_2.png', 'width': 620, 'height': 460, 'x': 320, 'y': 110},
    'asset-3': {'title': '3.png', 'template': 'desktop/windows/image_file.html', 'src': '/static/img/assets/asset_3.png', 'width': 620, 'height': 460, 'x': 340, 'y': 130},
    'asset-game-1': {'title': 'игра 1.png', 'template': 'desktop/windows/image_file.html', 'src': '/static/img/assets/game_1.png', 'width': 620, 'height': 460, 'x': 360, 'y': 150},
    'trash': {
        'title': 'Корзина',
        'template': 'desktop/windows/trash.html',
        'width': 480,
        'height': 300,
        'x': 420,
        'y': 140,
    },
    'system-folder': {
        'title': 'system32_backup',
        'template': 'desktop/windows/system_folder.html',
        'width': 610,
        'height': 410,
        'x': 210,
        'y': 116,
    },
    'deleted-letter': {
        'title': 'deleted_letter.txt - Notepad',
        'template': 'desktop/windows/deleted_letter.html',
        'width': 560,
        'height': 360,
        'x': 330,
        'y': 130,
    },
    'goodtoseeyou-note': {
        'title': 'goodtoseeyou.txt - Notepad',
        'template': 'desktop/windows/goodtoseeyou.html',
        'width': 460,
        'height': 260,
        'x': 340,
        'y': 150,
    },
    'final-letter': {
        'title': 'needtogowiththeflow.txt - Notepad',
        'template': 'desktop/windows/final_letter.html',
        'width': 680,
        'height': 560,
        'x': 240,
        'y': 62,
    },
    'lost': {
        'title': '~lost memories',
        'template': 'desktop/windows/lost.html',
        'width': 420,
        'height': 260,
        'x': 300,
        'y': 170,
    },
}
